// <auto-generated />
using System;
using Fish.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fish.Infrastructure.Migrations
{
    [DbContext(typeof(FishContext))]
    partial class FishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedModelFishModel", b =>
                {
                    b.Property<int>("FeedsId")
                        .HasColumnType("integer");

                    b.Property<int>("FishesId")
                        .HasColumnType("integer");

                    b.HasKey("FeedsId", "FishesId");

                    b.HasIndex("FishesId");

                    b.ToTable("FishFeeds", (string)null);
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.AquariumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Aquariums");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FeedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FishDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FishId")
                        .HasColumnType("integer");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FishId")
                        .IsUnique();

                    b.ToTable("FishDetails");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FishModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AquariumId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPredatory")
                        .HasColumnType("boolean");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AquariumId");

                    b.ToTable("Fishes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FreshwaterFishModel", b =>
                {
                    b.HasBaseType("Fish.Infrastructure.Models.FishModel");

                    b.Property<double>("PhLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("PreferredTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("TankSize")
                        .HasColumnType("integer");

                    b.ToTable("FreshwaterFishes", (string)null);
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.MigratoryFishModel", b =>
                {
                    b.HasBaseType("Fish.Infrastructure.Models.FishModel");

                    b.Property<double>("MigrationDistance")
                        .HasColumnType("double precision");

                    b.Property<string>("MigrationSeason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SpawningGrounds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("MigratoryFishes", (string)null);
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.SaltwaterFishModel", b =>
                {
                    b.HasBaseType("Fish.Infrastructure.Models.FishModel");

                    b.Property<bool>("CoralReefCompatible")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxDepth")
                        .HasColumnType("integer");

                    b.Property<double>("SaltTolerance")
                        .HasColumnType("double precision");

                    b.ToTable("SaltwaterFishes", (string)null);
                });

            modelBuilder.Entity("FeedModelFishModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.FeedModel", null)
                        .WithMany()
                        .HasForeignKey("FeedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fish.Infrastructure.Models.FishModel", null)
                        .WithMany()
                        .HasForeignKey("FishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FishDetailsModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.FishModel", "Fish")
                        .WithOne("Details")
                        .HasForeignKey("Fish.Infrastructure.Models.FishDetailsModel", "FishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fish");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FishModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.AquariumModel", "Aquarium")
                        .WithMany("Fishes")
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aquarium");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FreshwaterFishModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.FishModel", null)
                        .WithOne()
                        .HasForeignKey("Fish.Infrastructure.Models.FreshwaterFishModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.MigratoryFishModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.FishModel", null)
                        .WithOne()
                        .HasForeignKey("Fish.Infrastructure.Models.MigratoryFishModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.SaltwaterFishModel", b =>
                {
                    b.HasOne("Fish.Infrastructure.Models.FishModel", null)
                        .WithOne()
                        .HasForeignKey("Fish.Infrastructure.Models.SaltwaterFishModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.AquariumModel", b =>
                {
                    b.Navigation("Fishes");
                });

            modelBuilder.Entity("Fish.Infrastructure.Models.FishModel", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
